services:
  django-helper:
    build:
      context: ./django-admin-helper
    volumes:
      - ./backend:/workspace
    entrypoint: ["django-admin"]
    profiles:
      - starter

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # environment:
    #   - DJANGO_SETTINGS_MODULE=myproject.settings  # Update if your project name is different
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=random333
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../db_data:/var/lib/postgresql/data
